[package]
name = "ropp"
description = "Roblox Pre/Post Publishing"
version = "0.1.0"
authors = ["Kampfkarren"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
reqwest = "0.9"
rpassword = "3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "3.0"